LBHackney-IT/Manage_a_tenancy_API

ManageATenancyAPI.Tests/Actions/ETRAMeetingsActionTest.cs, ManageATenancyAPI.Tests/Unit/Controllers/ETRAControllerTest.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs, ManageATenancyAPI/Controllers/Housing/NHO/ETRAController.cs, ManageATenancyAPI/Helpers/Housing/HousingAPIQueryBuilder.cs, ManageATenancyAPI/Interfaces/Housing/IETRAMeetingsAction.cs, ManageATenancyAPI/ManageATenancyAPI.xml, ManageATenancyAPI/Models/Housing/NHO/ETRA.cs
amended endpoint to accomodate creation of ETRA issues
amended get tenancy interactions query to return interactions regardless of contact being linked or not
=> Create ETRA issues

ManageATenancyAPI.Tests/Actions/ETRAMeetingsActionTest.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs
Amended create ETRA meeting endpoint to return annotation id and incident id as part of the returned object
=> Amended create ETRA meeting endpoint

ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs, ManageATenancyAPI/Controllers/Housing/NHO/ETRAController.cs, ManageATenancyAPI/Helpers/Housing/HousingAPIQueryBuilder.cs
Update ETRA issue API covering scenarios:
Scenario: update existing note 
Scenario: Add new note 
Scenario: Delete issue
Scenario: Add note and update service area
Scenario: Update service area
Scenario: Add response and change status
Also, amended Get ETRA Issues api to return service area
=> Final amends to update etra issue

ManageATenancyAPI/Controllers/HealthCheckController.cs
What:
- HealthCheck Controller
Why:
- Check api is available for consumption
=> Add HealthCheck Controller

ManageATenancyAPI.Database/Properties/launchSettings.json, ManageATenancyAPI.Tests/ManageATenancyAPI.Tests.csproj, ManageATenancyAPI.Tests/Unit/Services/JWTServiceTests.cs, ManageATenancyAPI.v3.ncrunchsolution, ManageATenancyAPI/Controllers/CitizenIndexSearchController.cs, ManageATenancyAPI/Controllers/ConfigController.cs, ManageATenancyAPI/Controllers/Housing/AccountsController.cs, ManageATenancyAPI/Controllers/Housing/NHO/AreaPatchController.cs, ManageATenancyAPI/Controllers/Housing/NHO/BlockController.cs, ManageATenancyAPI/Controllers/Housing/NHO/ContactsController.cs, ManageATenancyAPI/Controllers/Housing/NHO/ETRAController.cs, ManageATenancyAPI/Controllers/Housing/NHO/EstateController.cs, ManageATenancyAPI/Controllers/Housing/NHO/LoginController.cs, ManageATenancyAPI/Controllers/Housing/NHO/OfficerAccountsController.cs, ManageATenancyAPI/Controllers/Housing/NHO/TRAController.cs, ManageATenancyAPI/Controllers/Housing/NHO/TenancyController.cs, ManageATenancyAPI/Controllers/Housing/NHO/TenancyManagementInteractionsController.cs, ManageATenancyAPI/Controllers/Housing/NHO/TraRoleController.cs, ManageATenancyAPI/Controllers/Housing/TransactionsController.cs, ManageATenancyAPI/Controllers/ValuesController.cs, ManageATenancyAPI/ManageATenancyAPI.csproj, ManageATenancyAPI/Program.cs, ManageATenancyAPI/Services/JWT/IJWTService.cs, ManageATenancyAPI/Services/JWT/JWTService.cs, ManageATenancyAPI/Services/JWT/Models/IManageATenancyClaims.cs, ManageATenancyAPI/Services/JWT/Models/ManageATenancyClaims.cs, ManageATenancyAPI/Services/JWT/Serialization/Converter.cs, ManageATenancyAPI/Services/JWT/Serialization/ParseStringConverter.cs, ManageATenancyAPI/Services/JWT/Serialization/Serialize.cs, ManageATenancyAPI/Startup.cs
What:
- Add JWT token support to API
- Add Authorize headers to Controllers
- Pulling JWT Secret from Environment Variable
- Tests that check we can decrypt Token.
Why:
- So the React front end for ETRA can consume the API when it's hosted in AWS securely.
=> JWT Token Authentication

ManageATenancyAPI.Tests/v2/AcceptanceTests/GetEtraMeeting/GetEtraMeetingAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/AcceptanceTests/SaveETRAMeeting/SaveEtraMeetingAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/AcceptanceTests/SignOffMeeting/SignOffMeetingAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/Helper/SaveMeetingInputModelHelper.cs, ManageATenancyAPI.Tests/v2/UseCases/SaveMeeting/SaveMeetingUseCaseTests.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs, ManageATenancyAPI/Gateways/SaveMeeting/SaveEtraMeeting/SaveEtraMeetingGateway.cs, ManageATenancyAPI/Gateways/SaveMeeting/SaveEtraMeetingIssue/SaveEtraMeetingIssueGateway.cs, ManageATenancyAPI/ManageATenancyAPI.csproj, ManageATenancyAPI/Services/Email/EmailKeys.cs, ManageATenancyAPI/Services/Email/SendTraConfirmationEmailGateway.cs, ManageATenancyAPI/Services/HackneyGetCRM365Token.cs, ManageATenancyAPI/UseCases/Meeting/SaveMeeting/Boundary/IMeetingIssue.cs
Changed model, corrected Ids,changed testcases
=> Fix saving of meeting and Issues

ManageATenancyAPI/Actions/Housing/NHO/TenancyManagementActions.cs, ManageATenancyAPI/Controllers/v2/TraController.cs, ManageATenancyAPI/Helpers/Housing/HousingAPIQueryBuilder.cs, ManageATenancyAPI/Services/Housing/FakeHousingAPICall.cs, ManageATenancyAPI/Tests/Actions/Housing/NHO/TenancyManagementActionsTests.cs, ManageATenancyAPI/Tests/Integration/Housing/HousingIntegrationTests.cs
Added parent Interaction Id In GetTenancyManagementInteraction , To get the issues of a meeting Mat-58
=> Added parent interaction Id -changes for Mat 58

ManageATenancyAPI.Tests/v2/AcceptanceTests/AcceptanceTests.cs, ManageATenancyAPI.Tests/v2/AcceptanceTests/GetEtraMeeting/GetEtraMeetingAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/Controllers/Tra/TRAControllerSignOffMeetingTests.cs, ManageATenancyAPI/Controllers/v2/TraController.cs
What:
- Assign meeting Id from claims token
=> Assign meeting id

ManageATenancyAPI/Actions/Housing/AccountActions.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs
save date for after service area update and account retrieving address  issue
=> save date for after service area update and account retrieving address  issue

ManageATenancyAPI/Services/JWT/JWTService.cs
added code to get values from parameter name instead array index
=> added code to get values from parameter name instead array index

ManageATenancyAPI/Actions/Housing/NHO/TenancyManagementActions.cs, ManageATenancyAPI/Helpers/Housing/HousingAPIQueryBuilder.cs, ManageATenancyAPI/Services/Housing/FakeHousingAPICall.cs, ManageATenancyAPI/Tests/Actions/Housing/NHO/TenancyManagementActionsTests.cs
Added issue location and traid to get tenancy management interaction .Test fixes.
=> Added issue location and traid

ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs
=> checking null for CRM data

ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs
Adding Projected Completion Date for the issue
=> Adding Projected Completion Date for the issue

ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs
Grouping data as one interaction item can have many notes.
=> Grouping data as one interaction item can have many notes

ManageATenancyAPI.Tests/v2/AcceptanceTests/GetEtraMeeting/GetEtraMeetingAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/UseCases/SaveMeeting/SaveMeetingUseCaseTests.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs, ManageATenancyAPI/Configuration/EmailConfiguration.cs, ManageATenancyAPI/Extension/ServiceConfiguration.cs, ManageATenancyAPI/Gateways/CloseMeeting/CloseETRAMeetingGateway.cs, ManageATenancyAPI/Gateways/CloseMeeting/ICloseETRAMeetingGateway.cs, ManageATenancyAPI/Gateways/SaveMeeting/SaveEtraMeeting/ISaveEtraMeetingGateway.cs, ManageATenancyAPI/Gateways/SaveMeeting/SaveEtraMeeting/SaveEtraMeetingGateway.cs, ManageATenancyAPI/Interfaces/Housing/IETRAMeetingsAction.cs, ManageATenancyAPI/ManageATenancyAPI.xml, ManageATenancyAPI/Models/Housing/NHO/ETRA.cs, ManageATenancyAPI/Services/Email/SendTraConfirmationEmailGateway.cs, ManageATenancyAPI/Services/Email/SendTraConfirmationEmailInputModel.cs, ManageATenancyAPI/Services/JWT/JWTService.cs, ManageATenancyAPI/UseCases/Meeting/SaveMeeting/Boundary/SaveETRAMeetingOutputModel.cs, ManageATenancyAPI/UseCases/Meeting/SaveMeeting/SaveEtraMeetingUseCase.cs, ManageATenancyAPI/UseCases/Meeting/SignOffMeeting/SignOffMeetingUseCase.cs
added close meeting functionality and change Email template
=> added close meeting functionality and change Email template

ManageATenancyAPI/Startup.cs
Changed Name in Connection String as DB is now moved to AWS
=> Changed Name in Connection String as DB is now moved to AWS

ManageATenancyAPI.Tests/v2/AcceptanceTests/EscalateIssues/EscalateIssuesAcceptanceTests.cs, ManageATenancyAPI.Tests/v2/UseCases/EscalateIssues/EscalateIssuesUseCaseTests.cs, ManageATenancyAPI/Actions/Housing/NHO/ETRAMeetingsAction.cs, ManageATenancyAPI/Gateways/SendEscalationEmailGateway/SendEscalationEmailGateway.cs, ManageATenancyAPI/Gateways/SendEscalationEmailGateway/SendEscalationEmailInputModel.cs, ManageATenancyAPI/Helpers/Housing/HousingAPIQueryBuilder.cs, ManageATenancyAPI/Services/Email/EmailKeys.cs, ManageATenancyAPI/UseCases/Meeting/SaveMeeting/Boundary/EscalateMeetingIssueInputModel.cs
Escalate Issue sending email fixes
=> Escalate issue template chage implementation

ManageATenancyAPI/Configuration/EmailConfiguration.cs, ManageATenancyAPI/Gateways/SendEscalationEmailGateway/SendEscalationEmailGateway.cs
Escalation Template for Area housing managers Implemented
=> Escalation Template for Area housing managers Implemented

.circleci/config.yml
Update CircleCi workflow to use new development branch
=> add development and master branches to workflows

ManageATenancyAPI/Configuration/URLConfiguration.cs, ManageATenancyAPI/Services/HackneyGetCRM365Token.cs
Update CRM token service to use new cloud based API.
=> update to use different API

.circleci/config.yml
This updates the configuration to remove the dependency to on-premise API.
=> Update to use different CRM token API
